New ret t2750 search network soc name
ATM-Consulting/dolibarr_module_network pull request #10
Opened 2021-02-09 14:24 UTC by atm-lena

- Ajout du nom de la société du contact dans la liste de recherche des liens network en cas de noms similaires
- Exclusion du contact courant dans la liste de recherche des liens network

2021-02-09 16:28 UTC, atm-john commented on CHANGELOG
> +v3.1 (9 feb. 2021)
le fichier changelog doit être nommé **ChangeLog.md**  pour être compatible Dolibarr

2021-02-09 16:37 UTC, atm-john requested changes

2021-02-09 16:37 UTC, atm-john commented on class/network.class.php
> +    public function getSearchResult($queryString, $TExclude)
Tu rajoute un paramètre obligatoire, dans l'absolu l'appel à getSearchResult par d'autres modules (ou parties du même module) fait planté c'est voulu ?

Surtout que TExclude = array() et je pense suffisant, non ?

2021-02-09 16:37 UTC, atm-john commented on script/interface.php
> +    	$TExclude[] = GETPOST('fk_source');
tu as oublié de typer ton GETPOST

2021-02-09 16:37 UTC, atm-john commented on script/interface.php
> +        __out($object->getSearchResult(GETPOST('network_target'), $TExclude));
Idem

2021-02-09 16:38 UTC, atm-john commented on class/network.class.php
> +    public function getSearchResult($queryString, $TExclude)
Oubli pas la PHP doc

2021-02-10 08:45 UTC, atm-john commented on class/network.class.php
> +                if($obj->type == "Contact" && empty($conf->global->NETWORK_SHOW_SOCIETE_CONTACT)) {
NETWORK_HIDE_SOCIETE_CONTACT du coup non ?

2021-02-11 09:49 UTC, atm-lena commented on class/network.class.php
> +    public function getSearchResult($queryString, $TExclude)
En effet oublié de ne pas le rendre obligatoire car oublié de penser que c'est utiliser peut-être dans d'autres modules ><

2021-02-11 09:53 UTC, atm-john commented on admin/network_setup.php
> +setup_print_on_off('NETWORK_HIDE_SOCIETE_CONTACT', $langs->trans('NETWORK_HIDE_SOCIETE_CONTACT'));
pour info ya pas besoin de mettre le $langs->trans('NETWORK_HIDE_SOCIETE_CONTACT') le premier argument suffit

2021-02-11 09:54 UTC, atm-john commented on class/network.class.php
du coup tu as oublié la PHP doc

2021-02-11 09:56 UTC, atm-john commented on script/interface.php
> +    	__out($object->getSearchResult(GETPOST('network_target', 'string'), $TExclude));
string ? regarde la doc de GETPOST

2021-02-15 14:56 UTC, merged